### ISSUE TITLE
Required FireFox Download to pass "Hide Link" Spec

### ISSUE THREAD

**Issue by agdavid** [learn-co-students/your-own-js-and-css-in-rails-v-000#61]
Hi LV team, I had the proper code to pass the lab but it would not pass the tests until I downloaded FireFox.  Prior to downloading Firefox, it presented this error:

`  1) Hide Link Clicking on 'Click To Hide Me' hides itself
     Failure/Error: visit '/'

```
 Selenium::WebDriver::Error::WebDriverError:
   Could not find Firefox binary (os=macosx). Make sure Firefox is installed or set the path manually with Selenium::WebDriver::Firefox::Binary.path=`
```

Just wanted to inform you in case you wanted to address this so that people were not forced to download a new browser just to pass the specs. Thanks!

**Comment by morgvanny** [comment]
I downloaded firefox, and it launched during tests, did nothing, then timed out, and that test failed. The app behaves normally when I actually run rails s and visit the page. Not sure how to fix the test, or my environment to pass it.

**Comment by michaelsimon** [comment]
+1 for this. 
I was able to get this working by adding  `gem 'chromedriver-helper'` to my gemfile (and then `bundlie install`)

and the following at the very bottom of my rails_helper.rb file:
```ruby
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
