### ISSUE TITLE
Use var instead if let 

### ISSUE THREAD

**Issue by 12ew** [learn-co-students/your-own-js-and-css-in-rails-v-000#855]
If you don't use var instead of let/const in your hide.js, it fails

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
